{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-secret-store
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "wordpress-gke.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ required "Please specify externalSecrets.projectId" .Values.externalSecrets.projectId }}
      auth:
        workloadIdentity:
          clusterLocation: {{ required "Please specify externalSecrets.clusterLocation" .Values.externalSecrets.clusterLocation }}
          clusterName:  {{ required "Please specify externalSecrets.clusterName" .Values.externalSecrets.clusterName }}
          serviceAccountRef:
            name: {{ include "wordpress-gke.serviceAccountName" . }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "wordpress-gke.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Release.Name }}-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.backend.secretName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecrets.backend.secretName }}
{{- end }}

