apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-gke.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "wordpress-gke.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ .Release.Name }}
