{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress-gke.serviceAccountName" . }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcp_sa }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "wordpress-gke.labels" . | nindent 4 }}
{{- end }}
